name: ${project.name}
version: ${project.version}
author: ${author}
main: ${mainClass}
api-version: 1.13

commands:
  test:

description: Plugin created for SkillWars Network by Joansiitoh and others.